[main]

token = ""
port = 7942
hmac_key = ""
buildbot_key = ""
oauth_client_id = ""
oauth_client_secret = ""

[[repo]]

owner = ""
repo = ""

reviewers = ["barosl"]
buildbot_url = ""
builders = ["auto-linux", "auto-mac"]

master_branch = "master"
buildbot_branch = "auto"
tmp_branch = "tmp"
rollup_branch = "rollup"
